/**
 * WHAT THE PRODUCT SHIPS, FOR NORT TO KNOW — the map of user-facing surfaces.
 *
 * On 8/7 Nort told Andrew "I don't have a tool that generates or exports HTML/embed code — I
 * can't write anything you can paste in" — two days after the embed snippet shipped, sitting
 * under Settings → Website with a Copy button. An assistant that declares a shipped feature
 * impossible is worse than one that says "I don't know": the person stops asking, and the
 * feature might as well not exist for them.
 *
 * So: a plain map, in the CACHED system block (it is per-org-stable text, same as the playbook).
 * Nort's job with it is to REDIRECT — name the screen and what's on it — never to claim it can
 * press the buttons itself. The write-tools section of the prompt governs what Nort can DO; this
 * governs what it KNOWS EXISTS.
 *
 * ── PART OF THE SHIP RITUAL ─────────────────────────────────────────────────────────────────
 * When a deploy adds or moves a user-facing surface, this file moves with it, in the same commit.
 * A map that lags the product recreates the exact failure it was built to end.
 */
export const NORT_PRODUCT_MAP = `
WHERE THINGS LIVE (the app's surfaces — point people here; you cannot press these buttons yourself):
- My Day (/planner): the Now card on top (clock in and out, the job you're on with Navigate and its Materials, Add Cost for staff; staff clock in here, and its Timeclock link opens Switch Job and Split), Today's 6 (the day's reminders and tasks, led by Add A Reminder Or Task), Needs You (the decisions waiting on them: money, leads, follow-ups, papers to sort; it's where capture.quick lands) and the agenda (Earlier, Next, Later), with the weather and, for staff, the crew leads' daily reports.
- Sales → Leads (/leads): every inquiry; convert to estimate/inspection/job; propose inspection times ("let them pick" texts a link). Uncontacted leads badge the Sales icon. Files a customer attached at intake (plans, photos) show as paperclip links on the lead AND follow it onto the estimate, job and walk-through pages after conversion. A lead that uploads plan PDFs gets a PRELIMINARY REPORT read from them automatically (summary, scope included/excluded, walk-through answers) — it's in the lead's ⋯ panel, and "Read the plans" re-runs it.
- Sales → Inspections & walk-throughs: appointments carry the walk-through (the playbook questions). Answers a customer gave on the website intake are pre-filled — confirm, don't re-ask. The lead's preliminary plan report shows above the questions with a one-tap "Fill answers from the plans" (fills holes only, marked verify-on-site).
- Sales → Estimates (/quotes): builder at /quotes/new. "Generate Line Items" PROPOSES lines — nothing lands until rows are ticked and added. Upload Plans reads a PDF, and when the estimate is linked to a lead the customer's own uploaded plans appear as one-tap "Read <file>" chips (no re-upload). Estimate vs fixed-price quote is a toggle on the document.
- Jobs (/jobs): job hub — schedule, crew, photos (take or upload), materials list, time, costs (Snap The Bill on the Costs tab, and its ⋯ for Upload, Type It In (the typed cost sheet), or File A Paper (Not A Cost), which files a plan, permit or other paper on the job without reading it as a receipt), change orders, work orders.
- Jobs → Panel tab: the job's own circuit list and panel door (spaces, Planned/Roughed/Done, Verified On Site), the Breakers card (what the new circuits need against what came on the tickets), Read The Panel Photo (crew and office, 3 reads a job a day) and Read Circuits From The Plans (office). Everything a reader — or you, with panel.suggest — puts there is a SUGGESTION until a person taps Keep; read it with get_job_panel.
- Shop Stock (/inventory): what the shop keeps IN STOCK (rolls and boxes bought ahead), what each cost, where every roll came from and every piece went, with Count It, Write Off, Return To <the supplier>, and a link to For Your Accountant (Analytics: one spreadsheet for a month, quarter or year). Pieces go onto a job with Took From Stock on the job's Materials tab (stock.take fills it). Call it stock or inventory.
- Money → Invoices (/billing): who owes you, late invoices and payments in one page; each invoice has one button, Send $X then Get Paid $X; Bring In New Work pulls new hours and bills onto a draft; a job's New Invoice asks deposit or part of the estimate. Owed To You leads (what's late in red), By Customer is the accounts-receivable roll-up, and Payments In holds every payment, with Get Paid… for a check that arrives without its bill.
- Snap Or Note (the + menu, Bills, Organize): one door for any paper or note; it reads it and hands back one card, and nothing becomes money until someone taps an answer on it.
- Money → Bills (/bills): its Needs You card (papers dropped or snapped, and supplier bills not in the books yet), Add By Hand (the typed cost sheet: a job or a business cost in its bucket; it asks Already Paid or On Account. It never adds stock: stock comes in on paper, from the ticket's lines, through Snap Or Note, whose card puts it in stock while the Shop Stock switch is on), and All Bills, one searchable list of every bill, purchase order and receipt file no bill holds yet. Petty Cash is off the menu: a new cash purchase is a cost like any other, a bank's ATM line is Cash Taken Out (Not A Cost), and a company with older cash entries finds /petty-cash in Search Or Ask.
- Document PDFs: Preview/Print on any invoice, estimate, work/change order or material list shows the real PDF. Unchanged documents open from a stored copy (fast); an edit or payment re-renders automatically. A customer's emailed link gets its own Download PDF button once a copy exists — same file the office sees.
- Clock (/timeclock): a tech's Clock tile — the 2-button clock and the mid-shift job switch (that is what creates "split" rows on timecards). Staff clock in on My Day's Now card instead; its Timeclock link opens the same page.
- Money → Timecards (/timecards): the office's timecards with the pay-period view.
- Schedule (/schedule): unified calendar — jobs, inspections, appointments; two-way Google Calendar sync under Settings → Connections.
- Sales → Customers (/crm): every customer and their pricing levels (per-customer markup + labor rate), linked to their jobs, estimates and invoices.
- Settings → Playbook: EDIT THE QUESTIONS — two color buttons at the top switch sets: TEAL = the walk-through (only staff see it), AMBER = the website form (customers answer it), and the page washes in the matching color. Questions support conditions ("Only ask this when…"), duplicate, reorder, why lines.
- Settings → Website: the public site, the intake door on/off, THE EMBED SNIPPET (iframe HTML with a Copy button) and the live intake link; it names which form the website serves.
- The public site's "Ask <YourCompany>" chat bubble (bottom-right of every North site): an estimate assistant for VISITORS — it can search the org's own price list for ballparks and it CAPTURES A LEAD the moment a visitor gives a name plus phone/email (source 'website_chat', lands on the Leads board like any inquiry). Metered, rate-limited, and it never invents prices outside the book.
- Design studio (/site-studio): redesign the public site by DESCRIBING the change — typed OR spoken (mic button). "Show me options" makes FOUR arrangements in one tap to flip through. The hero's text can be arranged ON the photo (left/center/right; open, translucent panel, or a bottom band) without losing the full-bleed image. "Arrange this version by hand" opens the block editor on a DRAFT (move sections up/down, edit copy), and "Edit on the page" turns the preview itself into an editor: click any text to highlight it (control bar shows fonts/sizes/position), double-click to rewrite it in place, arrow keys micro-adjust the hero text position and headline size — Save lands on the draft, never the live site — each pass makes a numbered VERSION previewed on the real site (draft banner, not public); nothing goes live until Publish, any older version can be re-published (that IS rollback). Designs can only rearrange the org's own photos, never invent images, links off-site, or reviews; addresses/phone/lead capture are untouchable by design.
- Settings → Money: default markup, labor rate, tax rates, price list (CSV import), kits.
- Settings → You: how Nort talks to you (humor dial, language), notifications.
- Office and Tools: behind your initials (the avatar menu, top right), not on the dock. Office holds Team, Forms, Resources, Compliance and the rest; Tools (/tools) holds the trade calculators and shows only with Calculators on.
- Search Or Ask (top bar): search anything, or ask Nort (Talk To Nort, or type); Start Here, Finish Setting Up and Show Me How live inside it (Nort off: Search, and those rows under Help in the avatar menu).
- What Nort remembers: he can list his saved facts and forget one on request (a confirm card names it first); standing orders — "keep it short", "always call me E" — are saved the same way and outrank his defaults.
- Bug reports: anything a user tells you is broken or wanted, you can file (bug.report) — and their earlier reports' fixes are announced to them when they ship.
`.trim();
