-- 0186: THE INTAKE UPLOAD BUCKET — plans, drawings and photos from a stranger (2026-08-06)
--
-- Andrew (Vivian Builders): "when Yes, reveal an 'Upload your plans' file-upload button (PDF, JPG,
-- PNG, DWG), optional, multiple files allowed, 100MB cap for large plan sets." Erik: "same with
-- photos."
--
-- PRIVATE, unlike `lead-uploads`. That bucket is public because the site-chat hands its URLs to a
-- vision model; a customer's architectural drawings are a different thing entirely — they are the
-- contractor's competitive information and often the homeowner's property. Private + short-lived
-- signed links means a leaked URL dies on its own.
--
-- NO ANON RLS POLICY, deliberately. An anonymous visitor never writes here directly: a rate-limited
-- server route validates the handle, checks the door is actually ON, checks the extension and the
-- declared size, and mints a SIGNED UPLOAD URL for one exact path it chooses. That keeps the write
-- authority on our side of the wire — the browser can only fill the one slot we opened for it.
-- Staff read it back through signed download URLs generated by the service client.
--
-- 100MB matches the ask (a full plan set is genuinely large). The mime list stays permissive
-- because browsers report DWG as anything from image/vnd.dwg to application/octet-stream — the
-- REAL gate is the extension allowlist in the upload route, which is ours and cannot be spoofed by
-- a Content-Type header.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'intake-uploads',
  'intake-uploads',
  false,
  104857600, -- 100MB
  null       -- enforced by extension in the route; see the note above
)
on conflict (id) do update
  set public = false,
      file_size_limit = excluded.file_size_limit;
