-- ═══════════════════════════════════════════════════════════════════════════
-- Contractor North — migration 0223: "start it over" learns about change orders
--
-- cn-v820 adds a fourth import source, `change_orders`, whose keys are 'co:<id>'. This function's
-- tombstone-forgetting clause is an EXPLICIT ENUMERATION of source → key-prefix, not a generic
-- 'p_source || ":%"' pattern, so a new source silently falls through to the else branch and its
-- tombstones are kept forever.
--
-- The consequence is precise and invisible: an office that deletes a change-order line, then hits
-- the amber "Start it over", gets an import that rebuilds everything EXCEPT that line, reports
-- success, and never says a change order is missing from the invoice.
--
-- This is the identical bug 0204 shipped and this function's own comment records — it enumerated
-- bill:/po: and forgot the bli: family, so every itemized receipt line survived the reset and was
-- skipped. Adding a source without adding its branch here is now a two-for-two mistake.
--
-- Generated by taking pg_get_functiondef of the LIVE function and inserting ONE line, rather than
-- retyping it. An earlier reconstruction of this same function from memory was wrong in five ways
-- (return type, text[] vs jsonb, the advisory lock, the draft guard, the cn.importing flag).
-- ═══════════════════════════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION public.reset_import_source(p_invoice_id uuid, p_source text)
 RETURNS jsonb
 LANGUAGE plpgsql
AS $function$
declare
  v_status   text;
  v_cleared  integer := 0;
  v_forgot   integer := 0;
begin
  if p_source is null or p_source = '' then
    raise exception 'An import source is required.';
  end if;

  select status into v_status from public.invoices where id = p_invoice_id;
  if v_status is null then
    raise exception 'Invoice not found.';
  end if;
  -- Same law as every importer: a sent invoice is the customer's document now.
  if v_status <> 'draft' then
    raise exception 'This invoice has been sent — only a draft can be re-imported.';
  end if;

  perform pg_advisory_xact_lock(hashtext(p_invoice_id::text || ':' || p_source));

  -- Speak as the IMPORTER (0175's flag): otherwise the delete trigger reads this as a human
  -- removing lines and tombstones every key we are about to re-import.
  perform set_config('cn.importing', '1', true);

  delete from public.invoice_items
   where invoice_id = p_invoice_id
     and import_source = p_source;
  get diagnostics v_cleared = row_count;

  -- Forget the tombstones for THIS source only. Keys are '<source-ish>:<id>' — labor keys start
  -- 'labor:', quote keys 'quote:', and COSTS mints THREE families: 'po:<id>', 'bill:<id>'
  -- (including 'bill:<id>:remainder') and 'bli:<bill line id>', one per itemized receipt line —
  -- the common case since the receipt reader shipped. 0204 enumerated only bill:/po:, so every
  -- bli: tombstone survived the reset and the rebuilt import silently skipped those lines.
  update public.invoices i
     set dismissed_import_keys = (
           select coalesce(array_agg(k), '{}')
             from unnest(coalesce(i.dismissed_import_keys, '{}')) as k
            where case p_source
                    when 'labor' then k not like 'labor:%'
                    when 'costs' then (k not like 'bill:%' and k not like 'po:%' and k not like 'bli:%')
                    when 'quote' then k not like 'quote:%'
                    when 'change_orders' then k not like 'co:%'
                    else k not like p_source || ':%'
                  end
         )
   where i.id = p_invoice_id;
  get diagnostics v_forgot = row_count;

  return jsonb_build_object('cleared_lines', v_cleared, 'forgot_dismissals', v_forgot);
end;
$function$
;
